# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("PhotoRenamer")
        MainWindow.setFixedSize(1151, 706)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.output_pic = QtWidgets.QLabel(self.centralwidget)
        self.output_pic.setGeometry(QtCore.QRect(90, 20, 971, 501))
        self.output_pic.setStyleSheet("")
        self.output_pic.setText("")
        self.output_pic.setObjectName("output_pic")
        self.output_pic.setAlignment(QtCore.Qt.AlignCenter)
        self.but_choose = QtWidgets.QPushButton(self.centralwidget)
        self.but_choose.setGeometry(QtCore.QRect(0, 600, 121, 101))
        self.but_choose.setText("")
        self.but_choose.setObjectName("but_choose")
        self.but_choose.setIcon(QtGui.QIcon('picture/choose.png'))
        self.but_choose.setIconSize(QtCore.QSize(121, 101))
        self.old_name = QtWidgets.QLabel(self.centralwidget)
        self.old_name.setGeometry(QtCore.QRect(260, 570, 631, 41))
        self.old_name.setStyleSheet("")
        self.old_name.setFont(QtGui.QFont("Times", 18))
        self.old_name.setText("")
        self.old_name.setAlignment(QtCore.Qt.AlignCenter)
        self.old_name.setObjectName("old_name")
        self.new_name = QtWidgets.QTextEdit(self.centralwidget)
        self.new_name.setGeometry(QtCore.QRect(260, 640, 631, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.new_name.setFont(font)
        self.new_name.setObjectName("new_name")
        self.but_ok = QtWidgets.QPushButton(self.centralwidget)
        self.but_ok.setGeometry(QtCore.QRect(1030, 600, 121, 101))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(25)
        font.setItalic(False)
        font.setUnderline(False)
        font.setKerning(True)
        self.but_ok.setFont(font)
        self.but_ok.setObjectName("but_ok")
        self.but_con = QtWidgets.QPushButton(self.centralwidget)
        self.but_con.setGeometry(QtCore.QRect(1070, 260, 81, 61))
        self.but_con.setText("")
        self.but_con.setObjectName("but_con")
        self.but_con.setIcon(QtGui.QIcon('picture/cont.png'))
        self.but_con.setIconSize(QtCore.QSize(81, 61))
        self.but_ret = QtWidgets.QPushButton(self.centralwidget)
        self.but_ret.setGeometry(QtCore.QRect(0, 260, 81, 61))
        self.but_ret.setText("")
        self.but_ret.setObjectName("but_ret")
        self.but_ret.setIcon(QtGui.QIcon('picture/ret.png'))
        self.but_ret.setIconSize(QtCore.QSize(81, 61))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.but_ok.setText(_translate("MainWindow", "Готово"))

